apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: ${CLOUDFLARE_API_TOKEN_K8S_SECRET_NAME}
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        api-token: "{{ .cloudflare_api_token }}"
  data:
    - secretKey: cloudflare_api_token
      remoteRef:
        key: "${CLOUDFLARE_API_TOKEN_SECRET_NAME}"
