apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 15m
  targetNamespace: observability

  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      version: '85.1.1'
      interval: 1h

  install:
    remediation:
      retries: 3

  upgrade:
    remediation:
      retries: 3

  values:
    prometheusOperator:
      enabled: true
      resources:
        requests:
          cpu: 25m
          memory: 96Mi
        limits:
          cpu: 200m
          memory: 256Mi

    prometheus:
      enabled: true
      prometheusSpec:
        replicas: 1
        retention: 7d
        retentionSize: 8GB
        resources:
          requests:
            cpu: 50m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 768Mi
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn-observability
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi

    alertmanager:
      enabled: true
      alertmanagerSpec:
        replicas: 2
        storage: {}
        resources:
          requests:
            cpu: 10m
            memory: 48Mi
          limits:
            cpu: 100m
            memory: 128Mi

    grafana:
      enabled: true
      replicas: 1
      ingress:
        enabled: false
      persistence:
        enabled: false
      resources:
        requests:
          cpu: 25m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 384Mi
      sidecar:
        resources:
          requests:
            cpu: 5m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 128Mi
      additionalDataSources:
        - name: Loki
          type: loki
          access: proxy
          url: http://observability-loki-gateway.observability.svc.cluster.local
          jsonData:
            maxLines: 1000

    nodeExporter:
      enabled: true

    prometheus-node-exporter:
      resources:
        requests:
          cpu: 10m
          memory: 24Mi
        limits:
          cpu: 100m
          memory: 64Mi

    kubeEtcd:
      enabled: false
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: false

    defaultRules:
      create: true
      rules:
        etcd: false
        kubeControllerManager: false
        kubeProxy: false
        kubeSchedulerAlerting: false
        kubeSchedulerRecording: false
        windows: false
