apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 15m
  targetNamespace: external-dns

  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      version: '1.21.1'
      interval: 1h

  install:
    remediation:
      retries: 3

  upgrade:
    remediation:
      retries: 3

  values:
    provider:
      name: cloudflare

    sources:
      - gateway-httproute

    domainFilters:
      - "${BASE_DOMAIN}"

    policy: sync
    registry: txt
    txtOwnerId: "${EXTERNAL_DNS_TXT_OWNER_ID}"
    interval: 1m

    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: ${CLOUDFLARE_API_TOKEN_K8S_SECRET_NAME}
            key: api-token
